import { Box, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";
import { RegisterInputs } from "../../Components";
import { CustomButton } from "../../Components/Helpers";
import style from "./Register.module.scss";

/**
 *This component is used to register users in the system.
 * @author Du2Du
 */
const RegisterUser: React.FC = () => {
  return (
    <Box className={style.registerBody}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        className={style.boxRegister}
        p="6"
        bg="#fff"
        borderRadius="lg"
        border="1px"
        borderColor="#34aee7"
        d="flex"
        flexDir={"column"}
      >
        <Heading fontSize="24px" textColor="#666666" textAlign="center" pb={4}>
          Register now to access the website
        </Heading>
        <RegisterInputs paddingYItems={2} />
      </Box>
    </Box>
  );
};

export default RegisterUser;
