import React, { useState } from "react";
import { PhoneIcon } from "@chakra-ui/icons";
import {
  Box,
  Button,
  FormErrorMessage,
  Input,
  InputGroup,
  InputLeftElement,
  InputRightElement,
  Stack,
} from "@chakra-ui/react";
import Head from "next/head";
import style from "./Register.module.scss";

const RegisterUser: React.FC = () => {
  const [show, setShow] = useState(false);
  const handleClick = () => setShow(!show);

  const onChange =
    (setValue: React.Dispatch<React.SetStateAction<string>>) =>
    (ev: React.ChangeEvent<HTMLInputElement>) => {
      const { value } = ev.currentTarget;
      setValue(value);
    };

  const [nameValue, setNameValue] = useState("");
  const [emailValue, setEmailValue] = useState("");
  const [passwordValue, setPasswordValue] = useState("");
  const [phoneValue, setPhoneValue] = useState("");

  return (
    <div className={style.registerBody}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        className={style.boxRegister}
        p="4"
        borderRadius="lg"
        border="1px"
        borderColor="#34aee7"
        d="flex"
        flexDir={"column"}
      >
        <Stack d="flex" flexDir={"column"} bg="#fff" pb={4}>
          <Input
            type="text"
            value={nameValue}
            onChange={onChange(setNameValue)}
            placeholder="Name"
            size="lg"
          />

          <Input
            type="email"
            value={emailValue}
            onChange={onChange(setEmailValue)}
            placeholder="E-mail"
            size="lg"
          />

          <InputGroup size="md">
            <Input
              pr="4.5rem"
              type={show ? "text" : "password"}
              placeholder="Password"
              onChange={onChange(setPasswordValue)}
              value={passwordValue}
            />
            <InputRightElement width="4.5rem">
              <Button
                h="1.75rem"
                size="sm"
                onClick={handleClick}
                textColor={"#34aee7"}
              >
                {show ? "Hide" : "Show"}
              </Button>
            </InputRightElement>
          </InputGroup>

          <InputGroup>
            <InputLeftElement
              pointerEvents="none"
              children={<PhoneIcon color={"gray.300"} />}
            />
            <Input
              type="tel"
              onChange={onChange(setPhoneValue)}
              value={phoneValue}
              placeholder="Phone"
            />
          </InputGroup>
        </Stack>
        <Button
          textColor={"#34aee7"}
          bg="#fff"
          borderRadius="full"
          border="1px"
        >
          Register
        </Button>
      </Box>
    </div>
  );
};

export default RegisterUser;
