import { Box, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";
import { RegisterInputs } from "../register-inputs";
import style from "./Layout.module.css";

/**
 *This component is used to register/login users in the system.
 *
 * @param isRegister This param receives a boolean which, if true, will load the fields for user registration.
 *
 * @author Du2Du
 */
export const LayoutCredentials: React.FC<{ isRegister: boolean }> = ({
  isRegister = false,
}) => {
  const titleName = isRegister ? "Register" : "Login";

  return (
    <Box className={style.registerBody}>
      <Head>
        <title>{titleName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        className={style.boxRegister}
        p="6"
        bg="#fff"
        borderRadius="lg"
        border="1px"
        borderColor="#34aee7"
        d="flex"
        flexDir={"column"}
      >
        <Heading fontSize="24px" textColor="#666666" textAlign="center" pb={4}>
          {titleName} now to access the website
        </Heading>
        <RegisterInputs paddingYItems={2} isRegister={isRegister} />
      </Box>
    </Box>
  );
};
