import { Box } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { FooterHome, NavigateHome, SectionHome } from "../Components";
import styles from "../Styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="text-slate-50">
        <NavigateHome />
        <SectionHome />
        <FooterHome />
      </Box>
    </div>
  );
};

export default Home;
