import { Box } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { FooterHome, NavigateHome, SectionHome } from "../Components";
import styles from "../Styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className="text-slate-50 h-100">
        <NavigateHome />
        <SectionHome />
        <FooterHome />
      </Box>
      <div className="w-full absolute" style={{ bottom: 0 }}>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
          <path
            fill="#56caef"
            fill-opacity="1"
            d="M0,224L48,197.3C96,171,192,117,288,85.3C384,53,480,43,576,74.7C672,107,768,181,864,186.7C960,192,1056,128,1152,117.3C1248,107,1344,149,1392,170.7L1440,192L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"
          ></path>
        </svg>
      </div>
    </div>
  );
};

export default Home;
